<?xml version="1.0"?>
<robot name="bicycle_drive" xmlns:xacro="http://ros.org/wiki/xacro">

    <joint name="frame_lidar" type="fixed">
        <parent link="frame" />
        <child link="laser_frame" />
        <origin xyz="0 0 ${wheel_radius+0.01}" rpy="0 0 0" />
    </joint>

    <link name="laser_frame">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="0.01" radius="0.07" />
            </geometry>
            <material name="black" />
        </visual>
        <collision>
            <geometry>
                <cylinder length="0.01" radius="0.07" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.5" length="0.01" radius="0.07">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="laser_frame">
        <sensor name="laser" type="ray">
            <pose>0 0 0 0 0 0</pose>
            <visualize>false</visualize>
            <update_rate>9</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <resoluation>1</resoluation>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.12</min>
                    <max>10.0</max>
                    <resoluation>0.01</resoluation>
                </range>
            </ray>
            <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>--ros-args --remap ~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>laser_frame</frame_name>
            </plugin>
        </sensor>

        <material>Gazebo/Black</material>
    </gazebo>

</robot>